### PR TITLE
Preliminary work for touchscreen support

### PR DESCRIPTION
**Pull request by StCyr**
It's probably full of bugs and it breaks the dragging in my FF on MacOS but I think I had it working 2 times on my iPhone in landscape mode

Signed-off-by: Cyrille Bollu <cyrpub@bollu.be>

### CODE REVIEW

**Comment by BesrourMS** [comment]
Please Update index.twig first

**Comment by StCyr** [comment]
Can you give me a hint how I should update index.twig to implement horizontal scrolling on smartphone?

**Comment by BesrourMS** [comment]
Add the loop for mutliple sections in index.twig

**Comment by BesrourMS** [comment]
Add the loop for mutliple sections in index.twig

**Comment by StCyr** [comment]
I've already done that

**Comment by BesrourMS** [comment]
In the commit just main.js is changed, please check again

**Comment by StCyr** [comment]
I've added the following code in index.twig to create the additional sections:

```
                                {% for page in pages("sub") if not page.hidden %}
                                        <section class="panel spotlight medium right" id="{{ page.title }}">
                                                <div class="content">
                                                        <h2 class="major">{{ page.title }}</h2>
                                                        <div class="period">{{ page.meta.period }}</div>
                                                        <p>{{ page.id|content }}</p>
                                                </div>
                                                <div class="image filtered tinted" data-position="top left">
                                                        <img src="{% if page.meta.image %}{{ page.meta.image }}{% else %}{{ theme_url }}/images/pic01.jpg{% endif %}" alt="{{ site_title }}" />
                                                </div>
                                        </section>
                                {% endfor %}
```

This works great: https://nextcloud.bollu.be/index.php/apps/cms_pico/pico/my_cv

But I don't see anything related to scrolling in index.twig

**Comment by BesrourMS** [comment]
The problem is in the commit I have just main.js and it's not logic to add your javascript modifications without enabling add many sections in index.twig

**Pull request closed without merging**
